### PR TITLE
update version in the plugin

### PR DESCRIPTION
**Pull request by yanxuYX**
update version in the plugin for 2.3.3
@BillChen-AI Hi Bill, I forgot to update the version in 2 other files. so not much in the PR just a version change

### CODE REVIEW

**Comment by BillChen-AI** [comment]
@yanxuYX ,
   Thanks for the PR. Agree the changes are trivial. 
   Is it possible to squash the two `Merge` commits so that the history of commits looks a bit nicer?
   You can try something like below, but if it's not working on your side, please let me know.

- Under your git branch:
```
  git log --oneline # This is to check the commits. You should see the two merge commits listed.
  git rebase -i ff01eb9 
``` 
- You may see a comment editor showing up, but depending on your git settings, you may see something different. 

image
 - If only one commit shown in the editor (as the screenshot below), you can just save and exit the editor.

`git log --oneline # You should now see the two merge commits are gone.`
- Assuming your origin is pointing to your forked repo:
 `git push -f origin HEAD` 
- PR should now have 1 commit.

**Comment by yanxuYX** [comment]
Hi Bill, 

Im seeing two commit when rebase to ff01eb9, it's because I reverted a commit 45ebf0f?

git

**Comment by yanxuYX** [comment]
Hi Bill, 
I did a git reset --soft HEAD~1
and did the git rebase -i ff01eb9 and it's showing only one commit now
but in the PR it is still 3.

**Comment by BillChen-AI** [comment]
Hi Yanxu (@yanxuYX ),
  Thanks for trying to resolve the extra commits. I'm not sure why after rebasing the extra commits still show up in the PR.
  I created a PR (Here: #71) based on your `master` branch. It has only one commit and the commit nicely shows the original author (you):
   
image
 
  If you are OK, you can go to that PR (#71), review it and verify that the changes are exactly the same as the changes in PR #70. Then make a comment there and I'll merge #71. We can then close this #70 .
 What do you think?

Also, I know why the extra commits happened: you work directly on your `master` branch.
Next time, if you can, please create a new branch (people call this kind of branch "feature branch") from `master` branch:
`git checkout -b MyNewBranchNameThatFixesSomething`
Then after you're done with code changes, `git push -u origin HEAD`. 
You can then create a PR from this feature branch.
After PR is merged, `git checkout master`, then `git pull upstream master`.
(In the above commands, the assumption is that, remote name `origin` points to your repo; `upstream` points to AQI's repo. )
That should make the commits clean.
Let me know if you have questions.

**Comment by BillChen-AI** [comment]
Hi Yanxu (@yanxuYX ),
  Thanks for confirming PR #71 is good to merge. I have done that and am closing this one (PR #70).

**Pull request closed without merging**
